### PR TITLE
Update to backtick-text-selector master code

### PR DESCRIPTION
**Pull request by jgoldfed**
I couldn't get backtick-text-selector to work on my side--it kept selecting the outer backticks when what I really wanted it to do was select the inside tick marks.  The code is what I came up with (with support of ChatGPT).  Let me know if this is the right direction. If no one else is having the issue, then it was me.

### CODE REVIEW

**Comment by cool-RR** [comment]
Thank you. I've indeed seen a few bugs with the code I've written and I hope these are the bugs you found as well. I think you should give a few examples of the documents where these bugs happened. (You should probably remove your personal content from them.) For each example you should also say where you placed the caret.

**Comment by jgoldfed** [comment]
[How to Install Scoop.md](https://github.com/user-attachments/files/17155991/How.to.Install.Scoop.md)

Just do ALT-', ALT-SHIFT-" anywhere on the page and you'll see it select outside the backticks.  No PII on this page.

**Comment by cool-RR** [comment]
Good job.

**Comment by cool-RR** [comment]
@jgoldfed The new version is now available for use. Sorry it took me a while to figure out how to release a new version.

**Pull request merged**
